version: '3.8'

services:
  api:
    container_name: zunnavi_api
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: local
    environment:
      STAGE: ${STAGE}
      API_PORT: ${API_PORT}
    volumes:
      - ./backend:/backend
    restart: always
    tty: true
    ports:
      - "${API_PORT}:${API_PORT}"
