version: '3.8'

services:
  sender:
    container_name: zunavi_sender
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: local
    environment:
      SENDER_API_PORT: ${SENDER_API_PORT}
      STAGE: ${STAGE}
      API_PORT: ${API_PORT}
      PUBSUB_ADDR: ${PUBSUB_ADDR}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - ./backend:/backend
    restart: always
    tty: true
    ports:
      - "${SENDER_API_PORT}:${SENDER_API_PORT}"
  voicer:
    container_name: zunavi_voicer
    image: "voicevox/voicevox_engine:cpu-ubuntu20.04-latest"
    ports:
      - "${VOICER_PORT}:50021"
  pubsub:
    container_name: zunavi_pubsub
    image: "redis:6.2.5-alpine"
    ports:
      - "${PUBSUB_PORT}:6379"
    volumes:
      - "./data/redis:/data"
